# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.AdvancedGameStat do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :gameId,
    :season,
    :week,
    :team,
    :opponent,
    :offense,
    :defense
  ]

  @type t :: %__MODULE__{
          :gameId => integer() | nil,
          :season => integer() | nil,
          :week => integer() | nil,
          :team => String.t() | nil,
          :opponent => String.t() | nil,
          :offense => Redshirt.Model.AdvancedGameStatOffense.t() | nil,
          :defense => Redshirt.Model.AdvancedGameStatOffense.t() | nil
        }
end

defimpl Poison.Decoder, for: Redshirt.Model.AdvancedGameStat do
  import Redshirt.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:offense, :struct, Redshirt.Model.AdvancedGameStatOffense, options)
    |> deserialize(:defense, :struct, Redshirt.Model.AdvancedGameStatOffense, options)
  end
end
