# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.AdvancedGameStatOffense do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :plays,
    :drives,
    :ppa,
    :totalPPA,
    :successRate,
    :explosiveness,
    :powerSuccess,
    :stuffRate,
    :lineYards,
    :lineYardsTotal,
    :secondLevelYards,
    :secondLevelYardsTotal,
    :openFieldYards,
    :openFieldYardsTotal,
    :standardDowns,
    :passingDowns,
    :rushingPlays,
    :passingPlays
  ]

  @type t :: %__MODULE__{
          :plays => integer() | nil,
          :drives => integer() | nil,
          :ppa => float() | nil,
          :totalPPA => float() | nil,
          :successRate => float() | nil,
          :explosiveness => float() | nil,
          :powerSuccess => float() | nil,
          :stuffRate => float() | nil,
          :lineYards => float() | nil,
          :lineYardsTotal => float() | nil,
          :secondLevelYards => float() | nil,
          :secondLevelYardsTotal => integer() | nil,
          :openFieldYards => float() | nil,
          :openFieldYardsTotal => integer() | nil,
          :standardDowns => Redshirt.Model.AdvancedGameStatOffenseStandardDowns.t() | nil,
          :passingDowns => Redshirt.Model.AdvancedGameStatOffenseStandardDowns.t() | nil,
          :rushingPlays => Redshirt.Model.AdvancedGameStatOffenseRushingPlays.t() | nil,
          :passingPlays => Redshirt.Model.AdvancedGameStatOffenseRushingPlays.t() | nil
        }
end

defimpl Poison.Decoder, for: Redshirt.Model.AdvancedGameStatOffense do
  import Redshirt.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :standardDowns,
      :struct,
      Redshirt.Model.AdvancedGameStatOffenseStandardDowns,
      options
    )
    |> deserialize(
      :passingDowns,
      :struct,
      Redshirt.Model.AdvancedGameStatOffenseStandardDowns,
      options
    )
    |> deserialize(
      :rushingPlays,
      :struct,
      Redshirt.Model.AdvancedGameStatOffenseRushingPlays,
      options
    )
    |> deserialize(
      :passingPlays,
      :struct,
      Redshirt.Model.AdvancedGameStatOffenseRushingPlays,
      options
    )
  end
end
