# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.AdvancedSeasonStatOffenseStandardDowns do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :rate,
    :ppa,
    :successRate,
    :explosiveness
  ]

  @type t :: %__MODULE__{
    :rate => float() | nil,
    :ppa => float() | nil,
    :successRate => float() | nil,
    :explosiveness => float() | nil
  }
end

defimpl Poison.Decoder, for: Redshirt.Model.AdvancedSeasonStatOffenseStandardDowns do
  def decode(value, _options) do
    value
  end
end

