# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.AdvancedSeasonStatOffense do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :plays,
    :drives,
    :ppa,
    :totalPPA,
    :successRate,
    :explosiveness,
    :powerSuccess,
    :stuffRate,
    :lineYards,
    :lineYardsTotal,
    :secondLevelYards,
    :secondLevelYardsTotal,
    :openFieldYards,
    :openFieldYardsTotal,
    :totalOpportunies,
    :pointsPerOpportunity,
    :fieldPosition,
    :havoc,
    :standardDowns,
    :passingDowns,
    :rushingPlays,
    :passingPlays
  ]

  @type t :: %__MODULE__{
          :plays => integer() | nil,
          :drives => integer() | nil,
          :ppa => float() | nil,
          :totalPPA => float() | nil,
          :successRate => float() | nil,
          :explosiveness => float() | nil,
          :powerSuccess => float() | nil,
          :stuffRate => float() | nil,
          :lineYards => float() | nil,
          :lineYardsTotal => float() | nil,
          :secondLevelYards => float() | nil,
          :secondLevelYardsTotal => integer() | nil,
          :openFieldYards => float() | nil,
          :openFieldYardsTotal => integer() | nil,
          :totalOpportunies => integer() | nil,
          :pointsPerOpportunity => float() | nil,
          :fieldPosition => Redshirt.Model.AdvancedSeasonStatOffenseFieldPosition.t() | nil,
          :havoc => Redshirt.Model.TeamSpRatingDefenseHavoc.t() | nil,
          :standardDowns => Redshirt.Model.AdvancedSeasonStatOffenseStandardDowns.t() | nil,
          :passingDowns => Redshirt.Model.AdvancedSeasonStatOffenseStandardDowns.t() | nil,
          :rushingPlays => Redshirt.Model.AdvancedSeasonStatOffenseRushingPlays.t() | nil,
          :passingPlays => Redshirt.Model.AdvancedSeasonStatOffenseRushingPlays.t() | nil
        }

  def model_structure do
    %__MODULE__{
      fieldPosition: Redshirt.Model.AdvancedSeasonStatOffenseFieldPosition.model_structure(),
      havoc: Redshirt.Model.TeamSpRatingDefenseHavoc.model_structure(),
      standardDowns: Redshirt.Model.AdvancedSeasonStatOffenseStandardDowns.model_structure(),
      passingDowns: Redshirt.Model.AdvancedSeasonStatOffenseStandardDowns.model_structure(),
      rushingPlays: Redshirt.Model.AdvancedSeasonStatOffenseRushingPlays.model_structure(),
      passingPlays: Redshirt.Model.AdvancedSeasonStatOffenseRushingPlays.model_structure()
    }
  end
end
