# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.BoxScoreTeamsScoringOpportunitiesInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :team,
    :opportunities,
    :points,
    :pointsPerOpportunity
  ]

  @type t :: %__MODULE__{
          :team => String.t() | nil,
          :opportunities => integer() | nil,
          :points => integer() | nil,
          :pointsPerOpportunity => float() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
