# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.BoxScoreTeams do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ppa,
    :cumulativePpa,
    :successRates,
    :explosiveness,
    :rushing,
    :havoc,
    :scoringOpportunities,
    :fieldPosition
  ]

  @type t :: %__MODULE__{
          :ppa => [Redshirt.Model.BoxScoreTeamsPpaInner.t()] | nil,
          :cumulativePpa => [Redshirt.Model.BoxScoreTeamsPpaInner.t()] | nil,
          :successRates => [Redshirt.Model.BoxScoreTeamsSuccessRatesInner.t()] | nil,
          :explosiveness => [Redshirt.Model.BoxScoreTeamsExplosivenessInner.t()] | nil,
          :rushing => [Redshirt.Model.BoxScoreTeamsRushingInner.t()] | nil,
          :havoc => [Redshirt.Model.BoxScoreTeamsHavocInner.t()] | nil,
          :scoringOpportunities =>
            [Redshirt.Model.BoxScoreTeamsScoringOpportunitiesInner.t()] | nil,
          :fieldPosition => [Redshirt.Model.BoxScoreTeamsFieldPositionInner.t()] | nil
        }

  def model_structure do
    %__MODULE__{
      ppa: [Redshirt.Model.BoxScoreTeamsPpaInner.model_structure()],
      cumulativePpa: [Redshirt.Model.BoxScoreTeamsPpaInner.model_structure()],
      successRates: [Redshirt.Model.BoxScoreTeamsSuccessRatesInner.model_structure()],
      explosiveness: [Redshirt.Model.BoxScoreTeamsExplosivenessInner.model_structure()],
      rushing: [Redshirt.Model.BoxScoreTeamsRushingInner.model_structure()],
      havoc: [Redshirt.Model.BoxScoreTeamsHavocInner.model_structure()],
      scoringOpportunities: [
        Redshirt.Model.BoxScoreTeamsScoringOpportunitiesInner.model_structure()
      ],
      fieldPosition: [Redshirt.Model.BoxScoreTeamsFieldPositionInner.model_structure()]
    }
  end
end
