# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.BoxScore do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :teams,
    :players
  ]

  @type t :: %__MODULE__{
          :teams => Redshirt.Model.BoxScoreTeams.t() | nil,
          :players => Redshirt.Model.BoxScorePlayers.t() | nil
        }

  def model_structure do
    %__MODULE__{
      teams: Redshirt.Model.BoxScoreTeams.model_structure(),
      players: Redshirt.Model.BoxScorePlayers.model_structure()
    }
  end
end
