# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.BoxScorePlayersUsageInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :player,
    :team,
    :position,
    :total,
    :quarter1,
    :quarter2,
    :quarter3,
    :quarter4,
    :rushing,
    :passing
  ]

  @type t :: %__MODULE__{
          :player => String.t() | nil,
          :team => String.t() | nil,
          :position => String.t() | nil,
          :total => float() | nil,
          :quarter1 => float() | nil,
          :quarter2 => float() | nil,
          :quarter3 => float() | nil,
          :quarter4 => float() | nil,
          :rushing => float() | nil,
          :passing => float() | nil
        }
end

defimpl Poison.Decoder, for: Redshirt.Model.BoxScorePlayersUsageInner do
  def decode(value, _options) do
    value
  end
end
