# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.BoxScorePlayersPpaInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :player,
    :team,
    :position,
    :average,
    :cumulative
  ]

  @type t :: %__MODULE__{
          :player => String.t() | nil,
          :team => String.t() | nil,
          :position => String.t() | nil,
          :average => Redshirt.Model.BoxScorePlayersPpaInnerAverage.t() | nil,
          :cumulative => Redshirt.Model.BoxScorePlayersPpaInnerAverage.t() | nil
        }

  def model_structure do
    %__MODULE__{
      average: Redshirt.Model.BoxScorePlayersPpaInnerAverage.model_structure(),
      cumulative: Redshirt.Model.BoxScorePlayersPpaInnerAverage.model_structure()
    }
  end
end
