# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.BoxScorePlayers do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :usage,
    :ppa
  ]

  @type t :: %__MODULE__{
          :usage => [Redshirt.Model.BoxScorePlayersUsageInner.t()] | nil,
          :ppa => [Redshirt.Model.BoxScorePlayersPpaInner.t()] | nil
        }
end

defimpl Poison.Decoder, for: Redshirt.Model.BoxScorePlayers do
  import Redshirt.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:usage, :list, Redshirt.Model.BoxScorePlayersUsageInner, options)
    |> deserialize(:ppa, :list, Redshirt.Model.BoxScorePlayersPpaInner, options)
  end
end
