# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.BoxScoreTeamsPpaInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :team,
    :plays,
    :overall,
    :passing,
    :rushing
  ]

  @type t :: %__MODULE__{
          :team => String.t() | nil,
          :plays => float() | nil,
          :overall => Redshirt.Model.BoxScoreTeamsPpaInnerOverall.t() | nil,
          :passing => Redshirt.Model.BoxScoreTeamsPpaInnerOverall.t() | nil,
          :rushing => Redshirt.Model.BoxScoreTeamsPpaInnerOverall.t() | nil
        }
end

defimpl Poison.Decoder, for: Redshirt.Model.BoxScoreTeamsPpaInner do
  import Redshirt.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:overall, :struct, Redshirt.Model.BoxScoreTeamsPpaInnerOverall, options)
    |> deserialize(:passing, :struct, Redshirt.Model.BoxScoreTeamsPpaInnerOverall, options)
    |> deserialize(:rushing, :struct, Redshirt.Model.BoxScoreTeamsPpaInnerOverall, options)
  end
end
