# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.BoxScorePlayers do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :usage,
    :ppa
  ]

  @type t :: %__MODULE__{
          :usage => [Redshirt.Model.BoxScorePlayersUsageInner.t()] | nil,
          :ppa => [Redshirt.Model.BoxScorePlayersPpaInner.t()] | nil
        }

  def model_structure do
    %__MODULE__{
      usage: [Redshirt.Model.BoxScorePlayersUsageInner.model_structure()],
      ppa: [Redshirt.Model.BoxScorePlayersPpaInner.model_structure()]
    }
  end
end
