# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.Coach do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :first_name,
    :last_name,
    :hire_date,
    :seasons
  ]

  @type t :: %__MODULE__{
    :first_name => String.t | nil,
    :last_name => String.t | nil,
    :hire_date => String.t | nil,
    :seasons => [Redshirt.Model.CoachSeasonsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: Redshirt.Model.Coach do
  import Redshirt.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:seasons, :list, Redshirt.Model.CoachSeasonsInner, options)
  end
end

