# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.ConferenceSpRating do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :year,
    :conference,
    :rating,
    :secondOrderWins,
    :sos,
    :offense,
    :defense,
    :specialTeams
  ]

  @type t :: %__MODULE__{
          :year => integer() | nil,
          :conference => String.t() | nil,
          :rating => float() | nil,
          :secondOrderWins => float() | nil,
          :sos => float() | nil,
          :offense => Redshirt.Model.ConferenceSpRatingOffense.t() | nil,
          :defense => Redshirt.Model.ConferenceSpRatingDefense.t() | nil,
          :specialTeams => Redshirt.Model.TeamSpRatingSpecialTeams.t() | nil
        }
end

defimpl Poison.Decoder, for: Redshirt.Model.ConferenceSpRating do
  import Redshirt.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:offense, :struct, Redshirt.Model.ConferenceSpRatingOffense, options)
    |> deserialize(:defense, :struct, Redshirt.Model.ConferenceSpRatingDefense, options)
    |> deserialize(:specialTeams, :struct, Redshirt.Model.TeamSpRatingSpecialTeams, options)
  end
end
