# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.ConferenceSpRatingOffense do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :rating,
    :success,
    :explosiveness,
    :rushing,
    :passing,
    :standardDowns,
    :passingDowns,
    :runRate,
    :pace
  ]

  @type t :: %__MODULE__{
    :rating => float() | nil,
    :success => float() | nil,
    :explosiveness => float() | nil,
    :rushing => float() | nil,
    :passing => float() | nil,
    :standardDowns => float() | nil,
    :passingDowns => float() | nil,
    :runRate => float() | nil,
    :pace => float() | nil
  }
end

defimpl Poison.Decoder, for: Redshirt.Model.ConferenceSpRatingOffense do
  def decode(value, _options) do
    value
  end
end

