# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.Conference do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :short_name,
    :abbreviation,
    :classification
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :name => String.t() | nil,
          :short_name => String.t() | nil,
          :abbreviation => String.t() | nil,
          :classification => String.t() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
