# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.DraftPick do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :collegeAthleteId,
    :nflAthleteId,
    :collegeId,
    :collegeTeam,
    :collegeConference,
    :nflTeam,
    :year,
    :overall,
    :round,
    :pick,
    :name,
    :position,
    :height,
    :weight,
    :preDraftRanking,
    :preDraftPositionRanking,
    :preDraftGrade,
    :hometownInfo
  ]

  @type t :: %__MODULE__{
          :collegeAthleteId => integer() | nil,
          :nflAthleteId => integer() | nil,
          :collegeId => integer() | nil,
          :collegeTeam => String.t() | nil,
          :collegeConference => String.t() | nil,
          :nflTeam => String.t() | nil,
          :year => integer() | nil,
          :overall => integer() | nil,
          :round => integer() | nil,
          :pick => integer() | nil,
          :name => String.t() | nil,
          :position => String.t() | nil,
          :height => integer() | nil,
          :weight => integer() | nil,
          :preDraftRanking => integer() | nil,
          :preDraftPositionRanking => integer() | nil,
          :preDraftGrade => integer() | nil,
          :hometownInfo => Redshirt.Model.DraftPickHometownInfo.t() | nil
        }

  def model_structure do
    %__MODULE__{
      hometownInfo: Redshirt.Model.DraftPickHometownInfo.model_structure()
    }
  end
end
