# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.DraftTeam do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :location,
    :nickname,
    :displayName,
    :logo
  ]

  @type t :: %__MODULE__{
          :location => String.t() | nil,
          :nickname => String.t() | nil,
          :displayName => String.t() | nil,
          :logo => String.t() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
