# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.DriveStartTime do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :minutes,
    :seconds
  ]

  @type t :: %__MODULE__{
          :minutes => integer() | nil,
          :seconds => integer() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
