# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.GameMedia do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :season,
    :week,
    :seasonType,
    :startTime,
    :isStartTimeTBD,
    :homeTeam,
    :homeConference,
    :awayTeam,
    :awayConference,
    :mediaType,
    :outlet
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :season => integer() | nil,
    :week => integer() | nil,
    :seasonType => String.t | nil,
    :startTime => String.t | nil,
    :isStartTimeTBD => boolean() | nil,
    :homeTeam => String.t | nil,
    :homeConference => String.t | nil,
    :awayTeam => String.t | nil,
    :awayConference => String.t | nil,
    :mediaType => String.t | nil,
    :outlet => String.t | nil
  }
end

defimpl Poison.Decoder, for: Redshirt.Model.GameMedia do
  def decode(value, _options) do
    value
  end
end

