# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.GameLinesLinesInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :provider,
    :spread,
    :formattedSpread,
    :spreadOpen,
    :overUnder,
    :overUnderOpen,
    :homeMoneyline,
    :awayMoneyline
  ]

  @type t :: %__MODULE__{
          :provider => String.t() | nil,
          :spread => float() | nil,
          :formattedSpread => String.t() | nil,
          :spreadOpen => float() | nil,
          :overUnder => float() | nil,
          :overUnderOpen => float() | nil,
          :homeMoneyline => float() | nil,
          :awayMoneyline => float() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
