# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.GameLines do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :season,
    :week,
    :seasonType,
    :startDate,
    :homeTeam,
    :homeConference,
    :homeScore,
    :awayTeam,
    :awayConference,
    :awayScore,
    :lines
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :season => integer() | nil,
          :week => integer() | nil,
          :seasonType => String.t() | nil,
          :startDate => String.t() | nil,
          :homeTeam => String.t() | nil,
          :homeConference => String.t() | nil,
          :homeScore => integer() | nil,
          :awayTeam => String.t() | nil,
          :awayConference => String.t() | nil,
          :awayScore => integer() | nil,
          :lines => [Redshirt.Model.GameLinesLinesInner.t()] | nil
        }

  def model_structure do
    %__MODULE__{
      lines: [Redshirt.Model.GameLinesLinesInner.model_structure()]
    }
  end
end
