# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.Game do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :season,
    :week,
    :season_type,
    :start_date,
    :start_time_tbd,
    :completed,
    :neutral_site,
    :conference_game,
    :attendance,
    :venue_id,
    :venue,
    :home_id,
    :home_team,
    :home_conference,
    :home_division,
    :home_points,
    :home_line_scores,
    :home_post_win_prob,
    :home_pregame_elo,
    :home_postgame_elo,
    :away_id,
    :away_team,
    :away_conference,
    :away_division,
    :away_points,
    :away_line_scores,
    :away_post_win_prob,
    :away_pregame_elo,
    :away_postgame_elo,
    :excitement_index,
    :highlights,
    :notes
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :season => integer() | nil,
          :week => integer() | nil,
          :season_type => String.t() | nil,
          :start_date => String.t() | nil,
          :start_time_tbd => boolean() | nil,
          :completed => boolean() | nil,
          :neutral_site => boolean() | nil,
          :conference_game => boolean() | nil,
          :attendance => integer() | nil,
          :venue_id => integer() | nil,
          :venue => String.t() | nil,
          :home_id => integer() | nil,
          :home_team => String.t() | nil,
          :home_conference => String.t() | nil,
          :home_division => String.t() | nil,
          :home_points => integer() | nil,
          :home_line_scores => [integer()] | nil,
          :home_post_win_prob => float() | nil,
          :home_pregame_elo => integer() | nil,
          :home_postgame_elo => integer() | nil,
          :away_id => integer() | nil,
          :away_team => String.t() | nil,
          :away_conference => String.t() | nil,
          :away_division => String.t() | nil,
          :away_points => integer() | nil,
          :away_line_scores => [integer()] | nil,
          :away_post_win_prob => float() | nil,
          :away_pregame_elo => integer() | nil,
          :away_postgame_elo => integer() | nil,
          :excitement_index => float() | nil,
          :highlights => String.t() | nil,
          :notes => String.t() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
