# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.LivePlayByPlay do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :status,
    :period,
    :clock,
    :possession,
    :down,
    :distance,
    :yardsToGoal,
    :teams,
    :drives
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :status => String.t() | nil,
          :period => integer() | nil,
          :clock => String.t() | nil,
          :possession => String.t() | nil,
          :down => integer() | nil,
          :distance => integer() | nil,
          :yardsToGoal => integer() | nil,
          :teams => [Redshirt.Model.LivePlayByPlayTeamsInner.t()] | nil,
          :drives => [Redshirt.Model.LivePlayByPlayDrivesInner.t()] | nil
        }

  def model_structure do
    %__MODULE__{
      teams: [Redshirt.Model.LivePlayByPlayTeamsInner.model_structure()],
      drives: [Redshirt.Model.LivePlayByPlayDrivesInner.model_structure()]
    }
  end
end
