# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.PlayType do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :text,
    :abbreviation
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :text => String.t | nil,
    :abbreviation => String.t | nil
  }
end

defimpl Poison.Decoder, for: Redshirt.Model.PlayType do
  def decode(value, _options) do
    value
  end
end

