# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.PlayStat do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :gameId,
    :season,
    :week,
    :team,
    :conference,
    :opponent,
    :teamScore,
    :opponentScore,
    :driveId,
    :playId,
    :period,
    :clock,
    :yardsToGoal,
    :down,
    :distance,
    :athleteId,
    :athleteName,
    :statType,
    :stat
  ]

  @type t :: %__MODULE__{
          :gameId => integer() | nil,
          :season => integer() | nil,
          :week => integer() | nil,
          :team => String.t() | nil,
          :conference => String.t() | nil,
          :opponent => String.t() | nil,
          :teamScore => integer() | nil,
          :opponentScore => integer() | nil,
          :driveId => integer() | nil,
          :playId => integer() | nil,
          :period => integer() | nil,
          :clock => Redshirt.Model.DriveStartTime.t() | nil,
          :yardsToGoal => integer() | nil,
          :down => integer() | nil,
          :distance => integer() | nil,
          :athleteId => integer() | nil,
          :athleteName => String.t() | nil,
          :statType => String.t() | nil,
          :stat => integer() | nil
        }

  def model_structure do
    %__MODULE__{
      clock: Redshirt.Model.DriveStartTime.model_structure()
    }
  end
end
