# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.PlayerSeasonPpa do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :season,
    :id,
    :name,
    :position,
    :team,
    :conference,
    :averagePPA,
    :totalPPA
  ]

  @type t :: %__MODULE__{
          :season => integer() | nil,
          :id => integer() | nil,
          :name => String.t() | nil,
          :position => String.t() | nil,
          :team => String.t() | nil,
          :conference => String.t() | nil,
          :averagePPA => Redshirt.Model.PlayerSeasonPpaAveragePpa.t() | nil,
          :totalPPA => Redshirt.Model.PlayerSeasonPpaAveragePpa.t() | nil
        }

  def model_structure do
    %__MODULE__{
      averagePPA: Redshirt.Model.PlayerSeasonPpaAveragePpa.model_structure(),
      totalPPA: Redshirt.Model.PlayerSeasonPpaAveragePpa.model_structure()
    }
  end
end
