# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.PlayerGame do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :teams
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :teams => [Redshirt.Model.PlayerGameTeamsInner.t()] | nil
        }

  def model_structure do
    %__MODULE__{
      teams: [Redshirt.Model.PlayerGameTeamsInner.model_structure()]
    }
  end
end
