# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.PlayerGameTeamsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :school,
    :homeAway,
    :points,
    :categories
  ]

  @type t :: %__MODULE__{
          :school => Redshirt.Model.PlayerGameTeamsInnerSchool.t() | nil,
          :homeAway => boolean() | nil,
          :points => integer() | nil,
          :categories => [Redshirt.Model.PlayerGameTeamsInnerCategoriesInner.t()] | nil
        }

  def model_structure do
    %__MODULE__{
      school: Redshirt.Model.PlayerGameTeamsInnerSchool.model_structure(),
      categories: [Redshirt.Model.PlayerGameTeamsInnerCategoriesInner.model_structure()]
    }
  end
end
