# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.PlayerGamePpa do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :season,
    :week,
    :name,
    :position,
    :team,
    :opponent,
    :averagePPA
  ]

  @type t :: %__MODULE__{
          :season => integer() | nil,
          :week => integer() | nil,
          :name => String.t() | nil,
          :position => String.t() | nil,
          :team => String.t() | nil,
          :opponent => String.t() | nil,
          :averagePPA => Redshirt.Model.PlayerGamePpaAveragePpa.t() | nil
        }

  def model_structure do
    %__MODULE__{
      averagePPA: Redshirt.Model.PlayerGamePpaAveragePpa.model_structure()
    }
  end
end
