# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.PlayerGameTeamsInnerCategoriesInnerTypesInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :athletes
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :athletes =>
            [Redshirt.Model.PlayerGameTeamsInnerCategoriesInnerTypesInnerAthletesInner.t()] | nil
        }

  def model_structure do
    %__MODULE__{
      athletes: [
        Redshirt.Model.PlayerGameTeamsInnerCategoriesInnerTypesInnerAthletesInner.model_structure()
      ]
    }
  end
end
