# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.PlayerUsage do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :season,
    :id,
    :name,
    :position,
    :team,
    :conference,
    :usage
  ]

  @type t :: %__MODULE__{
          :season => integer() | nil,
          :id => integer() | nil,
          :name => String.t() | nil,
          :position => String.t() | nil,
          :team => String.t() | nil,
          :conference => String.t() | nil,
          :usage => Redshirt.Model.PlayerUsageUsage.t() | nil
        }
end

defimpl Poison.Decoder, for: Redshirt.Model.PlayerUsage do
  import Redshirt.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:usage, :struct, Redshirt.Model.PlayerUsageUsage, options)
  end
end
