# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.PlayerUsage do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :season,
    :id,
    :name,
    :position,
    :team,
    :conference,
    :usage
  ]

  @type t :: %__MODULE__{
          :season => integer() | nil,
          :id => integer() | nil,
          :name => String.t() | nil,
          :position => String.t() | nil,
          :team => String.t() | nil,
          :conference => String.t() | nil,
          :usage => Redshirt.Model.PlayerUsageUsage.t() | nil
        }

  def model_structure do
    %__MODULE__{
      usage: Redshirt.Model.PlayerUsageUsage.model_structure()
    }
  end
end
