# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.PlayerGameTeamsInnerCategoriesInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :types
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :types => [Redshirt.Model.PlayerGameTeamsInnerCategoriesInnerTypesInner.t()] | nil
        }
end

defimpl Poison.Decoder, for: Redshirt.Model.PlayerGameTeamsInnerCategoriesInner do
  import Redshirt.Deserializer

  def decode(value, options) do
    value
    |> deserialize(
      :types,
      :list,
      Redshirt.Model.PlayerGameTeamsInnerCategoriesInnerTypesInner,
      options
    )
  end
end
