# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.PositionGroupRecruitingRating do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :team,
    :conference,
    :positionGroup,
    :averageRating,
    :totalRating,
    :commits,
    :averageStars
  ]

  @type t :: %__MODULE__{
          :team => String.t() | nil,
          :conference => String.t() | nil,
          :positionGroup => String.t() | nil,
          :averageRating => float() | nil,
          :totalRating => float() | nil,
          :commits => float() | nil,
          :averageStars => float() | nil
        }
end

defimpl Poison.Decoder, for: Redshirt.Model.PositionGroupRecruitingRating do
  def decode(value, _options) do
    value
  end
end
