# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.PredictedPoints do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :yardLine,
    :predictedPoints
  ]

  @type t :: %__MODULE__{
          :yardLine => integer() | nil,
          :predictedPoints => float() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
