# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.RankingWeekPollsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :poll,
    :ranks
  ]

  @type t :: %__MODULE__{
    :poll => String.t | nil,
    :ranks => [Redshirt.Model.RankingWeekPollsInnerRanksInner.t] | nil
  }
end

defimpl Poison.Decoder, for: Redshirt.Model.RankingWeekPollsInner do
  import Redshirt.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ranks, :list, Redshirt.Model.RankingWeekPollsInnerRanksInner, options)
  end
end

