# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.RankingWeek do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :season,
    :seasonType,
    :week,
    :polls
  ]

  @type t :: %__MODULE__{
          :season => integer() | nil,
          :seasonType => String.t() | nil,
          :week => integer() | nil,
          :polls => [Redshirt.Model.RankingWeekPollsInner.t()] | nil
        }

  def model_structure do
    %__MODULE__{
      polls: [Redshirt.Model.RankingWeekPollsInner.model_structure()]
    }
  end
end
