# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.RankingWeekPollsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :poll,
    :ranks
  ]

  @type t :: %__MODULE__{
          :poll => String.t() | nil,
          :ranks => [Redshirt.Model.RankingWeekPollsInnerRanksInner.t()] | nil
        }

  def model_structure do
    %__MODULE__{
      ranks: [Redshirt.Model.RankingWeekPollsInnerRanksInner.model_structure()]
    }
  end
end
