# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.ScoreboardGameBetting do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :spread,
    :overUnder,
    :homeMoneyline,
    :awayMoneyline
  ]

  @type t :: %__MODULE__{
          :spread => float() | nil,
          :overUnder => float() | nil,
          :homeMoneyline => integer() | nil,
          :awayMoneyline => integer() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
