# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.ScoreboardGameVenue do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :city,
    :state
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :city => String.t() | nil,
          :state => String.t() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
