# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.ScoreboardGame do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :startDate,
    :startTimeTBD,
    :tv,
    :neutralSite,
    :conferenceGame,
    :status,
    :period,
    :clock,
    :situation,
    :possession,
    :venue,
    :homeTeam,
    :awayTeam,
    :weather,
    :betting
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :startDate => String.t() | nil,
          :startTimeTBD => boolean() | nil,
          :tv => String.t() | nil,
          :neutralSite => boolean() | nil,
          :conferenceGame => boolean() | nil,
          :status => String.t() | nil,
          :period => integer() | nil,
          :clock => String.t() | nil,
          :situation => String.t() | nil,
          :possession => String.t() | nil,
          :venue => Redshirt.Model.ScoreboardGameVenue.t() | nil,
          :homeTeam => Redshirt.Model.ScoreboardGameHomeTeam.t() | nil,
          :awayTeam => Redshirt.Model.ScoreboardGameHomeTeam.t() | nil,
          :weather => Redshirt.Model.ScoreboardGameWeather.t() | nil,
          :betting => Redshirt.Model.ScoreboardGameBetting.t() | nil
        }

  def model_structure do
    %__MODULE__{
      venue: Redshirt.Model.ScoreboardGameVenue.model_structure(),
      homeTeam: Redshirt.Model.ScoreboardGameHomeTeam.model_structure(),
      awayTeam: Redshirt.Model.ScoreboardGameHomeTeam.model_structure(),
      weather: Redshirt.Model.ScoreboardGameWeather.model_structure(),
      betting: Redshirt.Model.ScoreboardGameBetting.model_structure()
    }
  end
end
