# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.ScoreboardGame do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :startDate,
    :startTimeTBD,
    :tv,
    :neutralSite,
    :conferenceGame,
    :status,
    :period,
    :clock,
    :situation,
    :possession,
    :venue,
    :homeTeam,
    :awayTeam,
    :weather,
    :betting
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :startDate => String.t | nil,
    :startTimeTBD => boolean() | nil,
    :tv => String.t | nil,
    :neutralSite => boolean() | nil,
    :conferenceGame => boolean() | nil,
    :status => String.t | nil,
    :period => integer() | nil,
    :clock => String.t | nil,
    :situation => String.t | nil,
    :possession => String.t | nil,
    :venue => Redshirt.Model.ScoreboardGameVenue.t | nil,
    :homeTeam => Redshirt.Model.ScoreboardGameHomeTeam.t | nil,
    :awayTeam => Redshirt.Model.ScoreboardGameHomeTeam.t | nil,
    :weather => Redshirt.Model.ScoreboardGameWeather.t | nil,
    :betting => Redshirt.Model.ScoreboardGameBetting.t | nil
  }
end

defimpl Poison.Decoder, for: Redshirt.Model.ScoreboardGame do
  import Redshirt.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:venue, :struct, Redshirt.Model.ScoreboardGameVenue, options)
    |> deserialize(:homeTeam, :struct, Redshirt.Model.ScoreboardGameHomeTeam, options)
    |> deserialize(:awayTeam, :struct, Redshirt.Model.ScoreboardGameHomeTeam, options)
    |> deserialize(:weather, :struct, Redshirt.Model.ScoreboardGameWeather, options)
    |> deserialize(:betting, :struct, Redshirt.Model.ScoreboardGameBetting, options)
  end
end

