# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.TeamSpRating do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :year,
    :team,
    :conference,
    :rating,
    :ranking,
    :secondOrderWins,
    :sos,
    :offense,
    :defense,
    :specialTeams
  ]

  @type t :: %__MODULE__{
          :year => integer() | nil,
          :team => String.t() | nil,
          :conference => String.t() | nil,
          :rating => float() | nil,
          :ranking => float() | nil,
          :secondOrderWins => float() | nil,
          :sos => float() | nil,
          :offense => Redshirt.Model.TeamSpRatingOffense.t() | nil,
          :defense => Redshirt.Model.TeamSpRatingDefense.t() | nil,
          :specialTeams => Redshirt.Model.TeamSpRatingSpecialTeams.t() | nil
        }

  def model_structure do
    %__MODULE__{
      offense: Redshirt.Model.TeamSpRatingOffense.model_structure(),
      defense: Redshirt.Model.TeamSpRatingDefense.model_structure(),
      specialTeams: Redshirt.Model.TeamSpRatingSpecialTeams.model_structure()
    }
  end
end
