# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.TeamPpaOffenseCumulative do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :total,
    :passing,
    :rushing
  ]

  @type t :: %__MODULE__{
          :total => float() | nil,
          :passing => float() | nil,
          :rushing => float() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
