# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.TeamTalent do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :year,
    :school,
    :talent
  ]

  @type t :: %__MODULE__{
          :year => integer() | nil,
          :school => String.t() | nil,
          :talent => float() | nil
        }
end

defimpl Poison.Decoder, for: Redshirt.Model.TeamTalent do
  def decode(value, _options) do
    value
  end
end
