# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.TeamRecord do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :year,
    :team,
    :conference,
    :division,
    :expectedWins,
    :total,
    :conferenceGames,
    :homeGames,
    :awayGames
  ]

  @type t :: %__MODULE__{
          :year => integer() | nil,
          :team => String.t() | nil,
          :conference => String.t() | nil,
          :division => String.t() | nil,
          :expectedWins => float() | nil,
          :total => Redshirt.Model.TeamRecordTotal.t() | nil,
          :conferenceGames => Redshirt.Model.TeamRecordTotal.t() | nil,
          :homeGames => Redshirt.Model.TeamRecordTotal.t() | nil,
          :awayGames => Redshirt.Model.TeamRecordTotal.t() | nil
        }

  def model_structure do
    %__MODULE__{
      total: Redshirt.Model.TeamRecordTotal.model_structure(),
      conferenceGames: Redshirt.Model.TeamRecordTotal.model_structure(),
      homeGames: Redshirt.Model.TeamRecordTotal.model_structure(),
      awayGames: Redshirt.Model.TeamRecordTotal.model_structure()
    }
  end
end
