# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.TeamMatchup do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :team1,
    :team2,
    :startYear,
    :endYear,
    :team1Wins,
    :team2Wins,
    :ties,
    :games
  ]

  @type t :: %__MODULE__{
    :team1 => String.t | nil,
    :team2 => String.t | nil,
    :startYear => integer() | nil,
    :endYear => integer() | nil,
    :team1Wins => integer() | nil,
    :team2Wins => integer() | nil,
    :ties => integer() | nil,
    :games => [Redshirt.Model.TeamMatchupGamesInner.t] | nil
  }
end

defimpl Poison.Decoder, for: Redshirt.Model.TeamMatchup do
  import Redshirt.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:games, :list, Redshirt.Model.TeamMatchupGamesInner, options)
  end
end

