# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.TeamMatchup do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :team1,
    :team2,
    :startYear,
    :endYear,
    :team1Wins,
    :team2Wins,
    :ties,
    :games
  ]

  @type t :: %__MODULE__{
          :team1 => String.t() | nil,
          :team2 => String.t() | nil,
          :startYear => integer() | nil,
          :endYear => integer() | nil,
          :team1Wins => integer() | nil,
          :team2Wins => integer() | nil,
          :ties => integer() | nil,
          :games => [Redshirt.Model.TeamMatchupGamesInner.t()] | nil
        }

  def model_structure do
    %__MODULE__{
      games: [Redshirt.Model.TeamMatchupGamesInner.model_structure()]
    }
  end
end
