# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.TeamRecordTotal do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :games,
    :wins,
    :losses,
    :ties
  ]

  @type t :: %__MODULE__{
    :games => integer() | nil,
    :wins => integer() | nil,
    :losses => integer() | nil,
    :ties => integer() | nil
  }
end

defimpl Poison.Decoder, for: Redshirt.Model.TeamRecordTotal do
  def decode(value, _options) do
    value
  end
end

