# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.TeamSpRatingDefenseHavoc do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :total,
    :frontSeven,
    :db
  ]

  @type t :: %__MODULE__{
    :total => float() | nil,
    :frontSeven => float() | nil,
    :db => float() | nil
  }
end

defimpl Poison.Decoder, for: Redshirt.Model.TeamSpRatingDefenseHavoc do
  def decode(value, _options) do
    value
  end
end

