# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.TeamPpaOffense do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :overall,
    :passing,
    :rushing,
    :firstDown,
    :secondDown,
    :thirdDown,
    :cumulative
  ]

  @type t :: %__MODULE__{
    :overall => float() | nil,
    :passing => float() | nil,
    :rushing => float() | nil,
    :firstDown => float() | nil,
    :secondDown => float() | nil,
    :thirdDown => float() | nil,
    :cumulative => Redshirt.Model.TeamPpaOffenseCumulative.t | nil
  }
end

defimpl Poison.Decoder, for: Redshirt.Model.TeamPpaOffense do
  import Redshirt.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:cumulative, :struct, Redshirt.Model.TeamPpaOffenseCumulative, options)
  end
end

