# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.TeamSpRatingOffense do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :ranking,
    :rating,
    :success,
    :explosiveness,
    :rushing,
    :passing,
    :standardDowns,
    :passingDowns,
    :runRate,
    :pace
  ]

  @type t :: %__MODULE__{
          :ranking => float() | nil,
          :rating => float() | nil,
          :success => float() | nil,
          :explosiveness => float() | nil,
          :rushing => float() | nil,
          :passing => float() | nil,
          :standardDowns => float() | nil,
          :passingDowns => float() | nil,
          :runRate => float() | nil,
          :pace => float() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
