# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.TeamSpRating do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :year,
    :team,
    :conference,
    :rating,
    :ranking,
    :secondOrderWins,
    :sos,
    :offense,
    :defense,
    :specialTeams
  ]

  @type t :: %__MODULE__{
    :year => integer() | nil,
    :team => String.t | nil,
    :conference => String.t | nil,
    :rating => float() | nil,
    :ranking => float() | nil,
    :secondOrderWins => float() | nil,
    :sos => float() | nil,
    :offense => Redshirt.Model.TeamSpRatingOffense.t | nil,
    :defense => Redshirt.Model.TeamSpRatingDefense.t | nil,
    :specialTeams => Redshirt.Model.TeamSpRatingSpecialTeams.t | nil
  }
end

defimpl Poison.Decoder, for: Redshirt.Model.TeamSpRating do
  import Redshirt.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:offense, :struct, Redshirt.Model.TeamSpRatingOffense, options)
    |> deserialize(:defense, :struct, Redshirt.Model.TeamSpRatingDefense, options)
    |> deserialize(:specialTeams, :struct, Redshirt.Model.TeamSpRatingSpecialTeams, options)
  end
end

