# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.TeamGameTeamsInnerStatsInner do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :category,
    :stat
  ]

  @type t :: %__MODULE__{
          :category => String.t() | nil,
          :stat => String.t() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
