# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.VenueLocation do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :x,
    :y
  ]

  @type t :: %__MODULE__{
          :x => float() | nil,
          :y => float() | nil
        }
end

defimpl Poison.Decoder, for: Redshirt.Model.VenueLocation do
  def decode(value, _options) do
    value
  end
end
