# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule Redshirt.Model.Week do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :season,
    :week,
    :seasonType,
    :firstGameStart,
    :lastGameStart
  ]

  @type t :: %__MODULE__{
          :season => integer() | nil,
          :week => integer() | nil,
          :seasonType => String.t() | nil,
          :firstGameStart => String.t() | nil,
          :lastGameStart => String.t() | nil
        }

  def model_structure do
    %__MODULE__{}
  end
end
