# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.AdvancedSeasonStatOffense do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :plays,
    :drives,
    :ppa,
    :totalPPA,
    :successRate,
    :explosiveness,
    :powerSuccess,
    :stuffRate,
    :lineYards,
    :lineYardsTotal,
    :secondLevelYards,
    :secondLevelYardsTotal,
    :openFieldYards,
    :openFieldYardsTotal,
    :totalOpportunies,
    :pointsPerOpportunity,
    :fieldPosition,
    :havoc,
    :standardDowns,
    :passingDowns,
    :rushingPlays,
    :passingPlays
  ]

  @type t :: %__MODULE__{
    :plays => integer() | nil,
    :drives => integer() | nil,
    :ppa => float() | nil,
    :totalPPA => float() | nil,
    :successRate => float() | nil,
    :explosiveness => float() | nil,
    :powerSuccess => float() | nil,
    :stuffRate => float() | nil,
    :lineYards => float() | nil,
    :lineYardsTotal => float() | nil,
    :secondLevelYards => float() | nil,
    :secondLevelYardsTotal => integer() | nil,
    :openFieldYards => float() | nil,
    :openFieldYardsTotal => integer() | nil,
    :totalOpportunies => integer() | nil,
    :pointsPerOpportunity => float() | nil,
    :fieldPosition => CollegeFootballDataAPI.Model.AdvancedSeasonStatOffenseFieldPosition.t | nil,
    :havoc => CollegeFootballDataAPI.Model.TeamSpRatingDefenseHavoc.t | nil,
    :standardDowns => CollegeFootballDataAPI.Model.AdvancedSeasonStatOffenseStandardDowns.t | nil,
    :passingDowns => CollegeFootballDataAPI.Model.AdvancedSeasonStatOffenseStandardDowns.t | nil,
    :rushingPlays => CollegeFootballDataAPI.Model.AdvancedSeasonStatOffenseRushingPlays.t | nil,
    :passingPlays => CollegeFootballDataAPI.Model.AdvancedSeasonStatOffenseRushingPlays.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.AdvancedSeasonStatOffense do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:fieldPosition, :struct, CollegeFootballDataAPI.Model.AdvancedSeasonStatOffenseFieldPosition, options)
    |> deserialize(:havoc, :struct, CollegeFootballDataAPI.Model.TeamSpRatingDefenseHavoc, options)
    |> deserialize(:standardDowns, :struct, CollegeFootballDataAPI.Model.AdvancedSeasonStatOffenseStandardDowns, options)
    |> deserialize(:passingDowns, :struct, CollegeFootballDataAPI.Model.AdvancedSeasonStatOffenseStandardDowns, options)
    |> deserialize(:rushingPlays, :struct, CollegeFootballDataAPI.Model.AdvancedSeasonStatOffenseRushingPlays, options)
    |> deserialize(:passingPlays, :struct, CollegeFootballDataAPI.Model.AdvancedSeasonStatOffenseRushingPlays, options)
  end
end

