# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.AdvancedSeasonStat do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :season,
    :team,
    :conference,
    :offense,
    :defense
  ]

  @type t :: %__MODULE__{
    :season => integer() | nil,
    :team => String.t | nil,
    :conference => String.t | nil,
    :offense => CollegeFootballDataAPI.Model.AdvancedSeasonStatOffense.t | nil,
    :defense => CollegeFootballDataAPI.Model.AdvancedSeasonStatOffense.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.AdvancedSeasonStat do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:offense, :struct, CollegeFootballDataAPI.Model.AdvancedSeasonStatOffense, options)
    |> deserialize(:defense, :struct, CollegeFootballDataAPI.Model.AdvancedSeasonStatOffense, options)
  end
end

