# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.BoxScorePlayersPpaInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :player,
    :team,
    :position,
    :average,
    :cumulative
  ]

  @type t :: %__MODULE__{
    :player => String.t | nil,
    :team => String.t | nil,
    :position => String.t | nil,
    :average => CollegeFootballDataAPI.Model.BoxScorePlayersPpaInnerAverage.t | nil,
    :cumulative => CollegeFootballDataAPI.Model.BoxScorePlayersPpaInnerAverage.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.BoxScorePlayersPpaInner do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:average, :struct, CollegeFootballDataAPI.Model.BoxScorePlayersPpaInnerAverage, options)
    |> deserialize(:cumulative, :struct, CollegeFootballDataAPI.Model.BoxScorePlayersPpaInnerAverage, options)
  end
end

