# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.BoxScoreTeamsPpaInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :team,
    :plays,
    :overall,
    :passing,
    :rushing
  ]

  @type t :: %__MODULE__{
    :team => String.t | nil,
    :plays => float() | nil,
    :overall => CollegeFootballDataAPI.Model.BoxScoreTeamsPpaInnerOverall.t | nil,
    :passing => CollegeFootballDataAPI.Model.BoxScoreTeamsPpaInnerOverall.t | nil,
    :rushing => CollegeFootballDataAPI.Model.BoxScoreTeamsPpaInnerOverall.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.BoxScoreTeamsPpaInner do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:overall, :struct, CollegeFootballDataAPI.Model.BoxScoreTeamsPpaInnerOverall, options)
    |> deserialize(:passing, :struct, CollegeFootballDataAPI.Model.BoxScoreTeamsPpaInnerOverall, options)
    |> deserialize(:rushing, :struct, CollegeFootballDataAPI.Model.BoxScoreTeamsPpaInnerOverall, options)
  end
end

