# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.BoxScoreTeamsRushingInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :team,
    :powerSuccess,
    :stuffRate,
    :lineYards,
    :lineYardsAverage,
    :secondLevelYards,
    :secondLevelYardsAverage,
    :openFieldYards,
    :openFieldYardsAverage
  ]

  @type t :: %__MODULE__{
    :team => String.t | nil,
    :powerSuccess => float() | nil,
    :stuffRate => float() | nil,
    :lineYards => float() | nil,
    :lineYardsAverage => float() | nil,
    :secondLevelYards => integer() | nil,
    :secondLevelYardsAverage => float() | nil,
    :openFieldYards => integer() | nil,
    :openFieldYardsAverage => float() | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.BoxScoreTeamsRushingInner do
  def decode(value, _options) do
    value
  end
end

