# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.BoxScorePlayers do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :usage,
    :ppa
  ]

  @type t :: %__MODULE__{
    :usage => [CollegeFootballDataAPI.Model.BoxScorePlayersUsageInner.t] | nil,
    :ppa => [CollegeFootballDataAPI.Model.BoxScorePlayersPpaInner.t] | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.BoxScorePlayers do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:usage, :list, CollegeFootballDataAPI.Model.BoxScorePlayersUsageInner, options)
    |> deserialize(:ppa, :list, CollegeFootballDataAPI.Model.BoxScorePlayersPpaInner, options)
  end
end

