# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.BoxScoreTeams do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :ppa,
    :cumulativePpa,
    :successRates,
    :explosiveness,
    :rushing,
    :havoc,
    :scoringOpportunities,
    :fieldPosition
  ]

  @type t :: %__MODULE__{
    :ppa => [CollegeFootballDataAPI.Model.BoxScoreTeamsPpaInner.t] | nil,
    :cumulativePpa => [CollegeFootballDataAPI.Model.BoxScoreTeamsPpaInner.t] | nil,
    :successRates => [CollegeFootballDataAPI.Model.BoxScoreTeamsSuccessRatesInner.t] | nil,
    :explosiveness => [CollegeFootballDataAPI.Model.BoxScoreTeamsExplosivenessInner.t] | nil,
    :rushing => [CollegeFootballDataAPI.Model.BoxScoreTeamsRushingInner.t] | nil,
    :havoc => [CollegeFootballDataAPI.Model.BoxScoreTeamsHavocInner.t] | nil,
    :scoringOpportunities => [CollegeFootballDataAPI.Model.BoxScoreTeamsScoringOpportunitiesInner.t] | nil,
    :fieldPosition => [CollegeFootballDataAPI.Model.BoxScoreTeamsFieldPositionInner.t] | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.BoxScoreTeams do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:ppa, :list, CollegeFootballDataAPI.Model.BoxScoreTeamsPpaInner, options)
    |> deserialize(:cumulativePpa, :list, CollegeFootballDataAPI.Model.BoxScoreTeamsPpaInner, options)
    |> deserialize(:successRates, :list, CollegeFootballDataAPI.Model.BoxScoreTeamsSuccessRatesInner, options)
    |> deserialize(:explosiveness, :list, CollegeFootballDataAPI.Model.BoxScoreTeamsExplosivenessInner, options)
    |> deserialize(:rushing, :list, CollegeFootballDataAPI.Model.BoxScoreTeamsRushingInner, options)
    |> deserialize(:havoc, :list, CollegeFootballDataAPI.Model.BoxScoreTeamsHavocInner, options)
    |> deserialize(:scoringOpportunities, :list, CollegeFootballDataAPI.Model.BoxScoreTeamsScoringOpportunitiesInner, options)
    |> deserialize(:fieldPosition, :list, CollegeFootballDataAPI.Model.BoxScoreTeamsFieldPositionInner, options)
  end
end

