# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.ConferenceSpRatingDefense do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :rating,
    :success,
    :explosiveness,
    :rushing,
    :pasing,
    :standardDowns,
    :passingDowns,
    :havoc
  ]

  @type t :: %__MODULE__{
    :rating => float() | nil,
    :success => float() | nil,
    :explosiveness => float() | nil,
    :rushing => float() | nil,
    :pasing => float() | nil,
    :standardDowns => float() | nil,
    :passingDowns => float() | nil,
    :havoc => CollegeFootballDataAPI.Model.TeamSpRatingDefenseHavoc.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.ConferenceSpRatingDefense do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:havoc, :struct, CollegeFootballDataAPI.Model.TeamSpRatingDefenseHavoc, options)
  end
end

