# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.ConferenceSpRating do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :year,
    :conference,
    :rating,
    :secondOrderWins,
    :sos,
    :offense,
    :defense,
    :specialTeams
  ]

  @type t :: %__MODULE__{
    :year => integer() | nil,
    :conference => String.t | nil,
    :rating => float() | nil,
    :secondOrderWins => float() | nil,
    :sos => float() | nil,
    :offense => CollegeFootballDataAPI.Model.ConferenceSpRatingOffense.t | nil,
    :defense => CollegeFootballDataAPI.Model.ConferenceSpRatingDefense.t | nil,
    :specialTeams => CollegeFootballDataAPI.Model.TeamSpRatingSpecialTeams.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.ConferenceSpRating do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:offense, :struct, CollegeFootballDataAPI.Model.ConferenceSpRatingOffense, options)
    |> deserialize(:defense, :struct, CollegeFootballDataAPI.Model.ConferenceSpRatingDefense, options)
    |> deserialize(:specialTeams, :struct, CollegeFootballDataAPI.Model.TeamSpRatingSpecialTeams, options)
  end
end

