# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.GameLines do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :season,
    :week,
    :seasonType,
    :startDate,
    :homeTeam,
    :homeConference,
    :homeScore,
    :awayTeam,
    :awayConference,
    :awayScore,
    :lines
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :season => integer() | nil,
    :week => integer() | nil,
    :seasonType => String.t | nil,
    :startDate => String.t | nil,
    :homeTeam => String.t | nil,
    :homeConference => String.t | nil,
    :homeScore => integer() | nil,
    :awayTeam => String.t | nil,
    :awayConference => String.t | nil,
    :awayScore => integer() | nil,
    :lines => [CollegeFootballDataAPI.Model.GameLinesLinesInner.t] | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.GameLines do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:lines, :list, CollegeFootballDataAPI.Model.GameLinesLinesInner, options)
  end
end

