# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.LivePlayByPlay do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :status,
    :period,
    :clock,
    :possession,
    :down,
    :distance,
    :yardsToGoal,
    :teams,
    :drives
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :status => String.t | nil,
    :period => integer() | nil,
    :clock => String.t | nil,
    :possession => String.t | nil,
    :down => integer() | nil,
    :distance => integer() | nil,
    :yardsToGoal => integer() | nil,
    :teams => [CollegeFootballDataAPI.Model.LivePlayByPlayTeamsInner.t] | nil,
    :drives => [CollegeFootballDataAPI.Model.LivePlayByPlayDrivesInner.t] | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.LivePlayByPlay do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:teams, :list, CollegeFootballDataAPI.Model.LivePlayByPlayTeamsInner, options)
    |> deserialize(:drives, :list, CollegeFootballDataAPI.Model.LivePlayByPlayDrivesInner, options)
  end
end

