# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.LivePlayByPlayTeamsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :teamId,
    :team,
    :homeAway,
    :points,
    :drives,
    :scoringOpportunities,
    :pointsPerOpportunity,
    :plays,
    :lineYards,
    :lineYardsPerRush,
    :secondLevelYards,
    :secondLevelYardsPerRush,
    :openFieldYards,
    :openFieldYardsPerRush,
    :epaPerPlay,
    :totalEpa,
    :passingEpa,
    :epaPerPass,
    :rushingEpa,
    :epaPerRush,
    :successRate,
    :standardDownSuccessRate,
    :passingDownSuccessRate,
    :explosiveness
  ]

  @type t :: %__MODULE__{
    :teamId => integer() | nil,
    :team => String.t | nil,
    :homeAway => String.t | nil,
    :points => integer() | nil,
    :drives => integer() | nil,
    :scoringOpportunities => integer() | nil,
    :pointsPerOpportunity => float() | nil,
    :plays => integer() | nil,
    :lineYards => integer() | nil,
    :lineYardsPerRush => float() | nil,
    :secondLevelYards => integer() | nil,
    :secondLevelYardsPerRush => float() | nil,
    :openFieldYards => integer() | nil,
    :openFieldYardsPerRush => float() | nil,
    :epaPerPlay => float() | nil,
    :totalEpa => float() | nil,
    :passingEpa => float() | nil,
    :epaPerPass => float() | nil,
    :rushingEpa => float() | nil,
    :epaPerRush => float() | nil,
    :successRate => float() | nil,
    :standardDownSuccessRate => float() | nil,
    :passingDownSuccessRate => float() | nil,
    :explosiveness => float() | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.LivePlayByPlayTeamsInner do
  def decode(value, _options) do
    value
  end
end

