# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.PlayerGame do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :teams
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :teams => [CollegeFootballDataAPI.Model.PlayerGameTeamsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.PlayerGame do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:teams, :list, CollegeFootballDataAPI.Model.PlayerGameTeamsInner, options)
  end
end

