# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.PlayerGameTeamsInnerSchool do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :conference
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :conference => String.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.PlayerGameTeamsInnerSchool do
  def decode(value, _options) do
    value
  end
end

