# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.PlayerSeasonStat do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :season,
    :playerId,
    :player,
    :team,
    :conference,
    :category,
    :statType,
    :stat
  ]

  @type t :: %__MODULE__{
    :season => integer() | nil,
    :playerId => integer() | nil,
    :player => String.t | nil,
    :team => String.t | nil,
    :conference => String.t | nil,
    :category => String.t | nil,
    :statType => String.t | nil,
    :stat => float() | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.PlayerSeasonStat do
  def decode(value, _options) do
    value
  end
end

