# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.PlayerSeasonPpa do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :season,
    :id,
    :name,
    :position,
    :team,
    :conference,
    :averagePPA,
    :totalPPA
  ]

  @type t :: %__MODULE__{
    :season => integer() | nil,
    :id => integer() | nil,
    :name => String.t | nil,
    :position => String.t | nil,
    :team => String.t | nil,
    :conference => String.t | nil,
    :averagePPA => CollegeFootballDataAPI.Model.PlayerSeasonPpaAveragePpa.t | nil,
    :totalPPA => CollegeFootballDataAPI.Model.PlayerSeasonPpaAveragePpa.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.PlayerSeasonPpa do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:averagePPA, :struct, CollegeFootballDataAPI.Model.PlayerSeasonPpaAveragePpa, options)
    |> deserialize(:totalPPA, :struct, CollegeFootballDataAPI.Model.PlayerSeasonPpaAveragePpa, options)
  end
end

