# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.PlayerGameTeamsInnerCategoriesInnerTypesInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :athletes
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :athletes => [CollegeFootballDataAPI.Model.PlayerGameTeamsInnerCategoriesInnerTypesInnerAthletesInner.t] | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.PlayerGameTeamsInnerCategoriesInnerTypesInner do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:athletes, :list, CollegeFootballDataAPI.Model.PlayerGameTeamsInnerCategoriesInnerTypesInnerAthletesInner, options)
  end
end

