# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.PlayerGamePpa do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :season,
    :week,
    :name,
    :position,
    :team,
    :opponent,
    :averagePPA
  ]

  @type t :: %__MODULE__{
    :season => integer() | nil,
    :week => integer() | nil,
    :name => String.t | nil,
    :position => String.t | nil,
    :team => String.t | nil,
    :opponent => String.t | nil,
    :averagePPA => CollegeFootballDataAPI.Model.PlayerGamePpaAveragePpa.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.PlayerGamePpa do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:averagePPA, :struct, CollegeFootballDataAPI.Model.PlayerGamePpaAveragePpa, options)
  end
end

