# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.PlayerGameTeamsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :school,
    :homeAway,
    :points,
    :categories
  ]

  @type t :: %__MODULE__{
    :school => CollegeFootballDataAPI.Model.PlayerGameTeamsInnerSchool.t | nil,
    :homeAway => boolean() | nil,
    :points => integer() | nil,
    :categories => [CollegeFootballDataAPI.Model.PlayerGameTeamsInnerCategoriesInner.t] | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.PlayerGameTeamsInner do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:school, :struct, CollegeFootballDataAPI.Model.PlayerGameTeamsInnerSchool, options)
    |> deserialize(:categories, :list, CollegeFootballDataAPI.Model.PlayerGameTeamsInnerCategoriesInner, options)
  end
end

