# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.RankingWeek do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :season,
    :seasonType,
    :week,
    :polls
  ]

  @type t :: %__MODULE__{
    :season => integer() | nil,
    :seasonType => String.t | nil,
    :week => integer() | nil,
    :polls => [CollegeFootballDataAPI.Model.RankingWeekPollsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.RankingWeek do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:polls, :list, CollegeFootballDataAPI.Model.RankingWeekPollsInner, options)
  end
end

