# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.RankingWeekPollsInnerRanksInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :rank,
    :school,
    :conference,
    :firstPlaceVotes,
    :points
  ]

  @type t :: %__MODULE__{
    :rank => integer() | nil,
    :school => String.t | nil,
    :conference => String.t | nil,
    :firstPlaceVotes => integer() | nil,
    :points => integer() | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.RankingWeekPollsInnerRanksInner do
  def decode(value, _options) do
    value
  end
end

