# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.ScoreboardGameVenue do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :city,
    :state
  ]

  @type t :: %__MODULE__{
    :name => String.t | nil,
    :city => String.t | nil,
    :state => String.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.ScoreboardGameVenue do
  def decode(value, _options) do
    value
  end
end

