# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.ScoreboardGameBetting do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :spread,
    :overUnder,
    :homeMoneyline,
    :awayMoneyline
  ]

  @type t :: %__MODULE__{
    :spread => float() | nil,
    :overUnder => float() | nil,
    :homeMoneyline => integer() | nil,
    :awayMoneyline => integer() | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.ScoreboardGameBetting do
  def decode(value, _options) do
    value
  end
end

