# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.TeamRecruitingRank do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :year,
    :rank,
    :team,
    :points
  ]

  @type t :: %__MODULE__{
    :year => integer() | nil,
    :rank => integer() | nil,
    :team => String.t | nil,
    :points => float() | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.TeamRecruitingRank do
  def decode(value, _options) do
    value
  end
end

