# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.TeamMatchupGamesInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :season,
    :week,
    :season_type,
    :date,
    :neutralSite,
    :venue,
    :homeTeam,
    :homeScore,
    :awayTeam,
    :awayScore,
    :winner
  ]

  @type t :: %__MODULE__{
    :season => integer() | nil,
    :week => integer() | nil,
    :season_type => String.t | nil,
    :date => String.t | nil,
    :neutralSite => boolean() | nil,
    :venue => String.t | nil,
    :homeTeam => String.t | nil,
    :homeScore => integer() | nil,
    :awayTeam => String.t | nil,
    :awayScore => integer() | nil,
    :winner => String.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.TeamMatchupGamesInner do
  def decode(value, _options) do
    value
  end
end

