# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.TeamLocation do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :venue_id,
    :name,
    :city,
    :state,
    :zip,
    :country_code,
    :timezone,
    :latitude,
    :longitude,
    :elevation,
    :capacity,
    :year_constructed,
    :grass,
    :dome
  ]

  @type t :: %__MODULE__{
    :venue_id => integer() | nil,
    :name => String.t | nil,
    :city => String.t | nil,
    :state => String.t | nil,
    :zip => String.t | nil,
    :country_code => String.t | nil,
    :timezone => String.t | nil,
    :latitude => float() | nil,
    :longitude => float() | nil,
    :elevation => float() | nil,
    :capacity => float() | nil,
    :year_constructed => float() | nil,
    :grass => boolean() | nil,
    :dome => boolean() | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.TeamLocation do
  def decode(value, _options) do
    value
  end
end

