# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.TeamSrsRating do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :year,
    :team,
    :conference,
    :division,
    :rating,
    :ranking
  ]

  @type t :: %__MODULE__{
    :year => integer() | nil,
    :team => String.t | nil,
    :conference => String.t | nil,
    :division => String.t | nil,
    :rating => float() | nil,
    :ranking => float() | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.TeamSrsRating do
  def decode(value, _options) do
    value
  end
end

