# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.TeamGameTeamsInner do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :school,
    :conference,
    :homeAway,
    :points,
    :stats
  ]

  @type t :: %__MODULE__{
    :school => String.t | nil,
    :conference => String.t | nil,
    :homeAway => String.t | nil,
    :points => integer() | nil,
    :stats => [CollegeFootballDataAPI.Model.TeamGameTeamsInnerStatsInner.t] | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.TeamGameTeamsInner do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:stats, :list, CollegeFootballDataAPI.Model.TeamGameTeamsInnerStatsInner, options)
  end
end

