# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.TeamRecord do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :year,
    :team,
    :conference,
    :division,
    :expectedWins,
    :total,
    :conferenceGames,
    :homeGames,
    :awayGames
  ]

  @type t :: %__MODULE__{
    :year => integer() | nil,
    :team => String.t | nil,
    :conference => String.t | nil,
    :division => String.t | nil,
    :expectedWins => float() | nil,
    :total => CollegeFootballDataAPI.Model.TeamRecordTotal.t | nil,
    :conferenceGames => CollegeFootballDataAPI.Model.TeamRecordTotal.t | nil,
    :homeGames => CollegeFootballDataAPI.Model.TeamRecordTotal.t | nil,
    :awayGames => CollegeFootballDataAPI.Model.TeamRecordTotal.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.TeamRecord do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:total, :struct, CollegeFootballDataAPI.Model.TeamRecordTotal, options)
    |> deserialize(:conferenceGames, :struct, CollegeFootballDataAPI.Model.TeamRecordTotal, options)
    |> deserialize(:homeGames, :struct, CollegeFootballDataAPI.Model.TeamRecordTotal, options)
    |> deserialize(:awayGames, :struct, CollegeFootballDataAPI.Model.TeamRecordTotal, options)
  end
end

