# NOTE: This file is auto generated by OpenAPI Generator 6.2.1 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule CollegeFootballDataAPI.Model.Venue do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :capacity,
    :grass,
    :city,
    :state,
    :zip,
    :country_code,
    :location,
    :elevation,
    :year_constructed,
    :dome,
    :timezone
  ]

  @type t :: %__MODULE__{
    :id => integer() | nil,
    :name => String.t | nil,
    :capacity => integer() | nil,
    :grass => boolean() | nil,
    :city => String.t | nil,
    :state => String.t | nil,
    :zip => String.t | nil,
    :country_code => String.t | nil,
    :location => CollegeFootballDataAPI.Model.VenueLocation.t | nil,
    :elevation => float() | nil,
    :year_constructed => integer() | nil,
    :dome => boolean() | nil,
    :timezone => String.t | nil
  }
end

defimpl Poison.Decoder, for: CollegeFootballDataAPI.Model.Venue do
  import CollegeFootballDataAPI.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:location, :struct, CollegeFootballDataAPI.Model.VenueLocation, options)
  end
end

